/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingSubscriptionItem {
    /// String representing the object's type
    #[serde(rename = "object")]
    pub object: Object,
    /// Unique identifier for the subscription item
    #[serde(rename = "id")]
    pub id: String,
    /// Unique identifier for the Clerk instance
    #[serde(rename = "instance_id")]
    pub instance_id: String,
    /// Current status of the subscription item
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "credit", skip_serializing_if = "Option::is_none")]
    pub credit: Option<Box<models::BillingSubscriptionCreditResponse>>,
    /// Unique identifier for the associated plan
    #[serde(rename = "plan_id")]
    pub plan_id: String,
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Box<models::BillingPlan>>,
    /// The billing period for this subscription
    #[serde(rename = "plan_period")]
    pub plan_period: PlanPeriod,
    /// Unique identifier for the payment method
    #[serde(rename = "payment_method_id", skip_serializing_if = "Option::is_none")]
    pub payment_method_id: Option<String>,
    #[serde(rename = "payment_method", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<Box<models::BillingPaymentMethod>>,
    #[serde(rename = "lifetime_paid", skip_serializing_if = "Option::is_none")]
    pub lifetime_paid: Option<Box<models::BillingFee>>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Box<models::BillingFee>>,
    #[serde(rename = "next_payment", skip_serializing_if = "Option::is_none")]
    pub next_payment: Option<Box<models::BillingSubscriptionItemNextPayment>>,
    /// Unique identifier for the payer
    #[serde(rename = "payer_id")]
    pub payer_id: String,
    #[serde(rename = "payer", skip_serializing_if = "Option::is_none")]
    pub payer: Option<Box<models::BillingPayer>>,
    /// Whether this subscription is currently on a free trial
    #[serde(rename = "is_free_trial")]
    pub is_free_trial: bool,
    /// Unix timestamp (in milliseconds) when the current period started
    #[serde(rename = "period_start")]
    pub period_start: i64,
    /// Unix timestamp (in milliseconds) when the current period ends
    #[serde(rename = "period_end", deserialize_with = "Option::deserialize")]
    pub period_end: Option<i64>,
    /// Date used for proration calculations
    #[serde(rename = "proration_date", skip_serializing_if = "Option::is_none")]
    pub proration_date: Option<String>,
    /// Unix timestamp (in milliseconds) when the subscription was canceled
    #[serde(rename = "canceled_at", deserialize_with = "Option::deserialize")]
    pub canceled_at: Option<i64>,
    /// Unix timestamp (in milliseconds) when the subscription became past due
    #[serde(rename = "past_due_at", deserialize_with = "Option::deserialize")]
    pub past_due_at: Option<i64>,
    /// Unix timestamp (in milliseconds) when the subscription ended
    #[serde(rename = "ended_at", deserialize_with = "Option::deserialize")]
    pub ended_at: Option<i64>,
    /// Unix timestamp (in milliseconds) when the subscription was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Unix timestamp (in milliseconds) when the subscription was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl BillingSubscriptionItem {
    pub fn new(object: Object, id: String, instance_id: String, status: Status, plan_id: String, plan_period: PlanPeriod, payer_id: String, is_free_trial: bool, period_start: i64, period_end: Option<i64>, canceled_at: Option<i64>, past_due_at: Option<i64>, ended_at: Option<i64>) -> BillingSubscriptionItem {
        BillingSubscriptionItem {
            object,
            id,
            instance_id,
            status,
            credit: None,
            plan_id,
            plan: None,
            plan_period,
            payment_method_id: None,
            payment_method: None,
            lifetime_paid: None,
            amount: None,
            next_payment: None,
            payer_id,
            payer: None,
            is_free_trial,
            period_start,
            period_end,
            proration_date: None,
            canceled_at,
            past_due_at,
            ended_at,
            created_at: None,
            updated_at: None,
        }
    }
}
/// String representing the object's type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "commerce_subscription_item")]
    CommerceSubscriptionItem,
}

impl Default for Object {
    fn default() -> Object {
        Self::CommerceSubscriptionItem
    }
}
/// Current status of the subscription item
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "ended")]
    Ended,
    #[serde(rename = "past_due")]
    PastDue,
    #[serde(rename = "upcoming")]
    Upcoming,
    #[serde(rename = "incomplete")]
    Incomplete,
    #[serde(rename = "abandoned")]
    Abandoned,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// The billing period for this subscription
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlanPeriod {
    #[serde(rename = "month")]
    Month,
    #[serde(rename = "annual")]
    Annual,
}

impl Default for PlanPeriod {
    fn default() -> PlanPeriod {
        Self::Month
    }
}

