/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingPlan {
    /// String representing the object's type
    #[serde(rename = "object")]
    pub object: Object,
    /// Unique identifier for the plan
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the plan
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "fee")]
    pub fee: Box<models::BillingFee>,
    /// The monthly equivalent when billed annually
    #[serde(rename = "annual_monthly_fee", deserialize_with = "Option::deserialize")]
    pub annual_monthly_fee: Option<Box<models::BillingFee>>,
    /// The annual fee for this plan
    #[serde(rename = "annual_fee", deserialize_with = "Option::deserialize")]
    pub annual_fee: Option<Box<models::BillingFee>>,
    /// The description of the plan
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    /// The ID of the product this plan belongs to
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Whether this is the default plan
    #[serde(rename = "is_default")]
    pub is_default: bool,
    /// Whether this is a recurring plan
    #[serde(rename = "is_recurring")]
    pub is_recurring: bool,
    /// Whether this plan is publicly visible
    #[serde(rename = "publicly_visible")]
    pub publicly_visible: bool,
    /// Whether this plan has a base fee
    #[serde(rename = "has_base_fee")]
    pub has_base_fee: bool,
    /// The payer type this plan is designed for
    #[serde(rename = "for_payer_type")]
    pub for_payer_type: String,
    /// The URL-friendly slug for the plan
    #[serde(rename = "slug")]
    pub slug: String,
    /// The URL of the plan's avatar image
    #[serde(rename = "avatar_url", deserialize_with = "Option::deserialize")]
    pub avatar_url: Option<String>,
    /// Whether free trial is enabled for this plan
    #[serde(rename = "free_trial_enabled")]
    pub free_trial_enabled: bool,
    /// Number of free trial days for this plan
    #[serde(rename = "free_trial_days", deserialize_with = "Option::deserialize")]
    pub free_trial_days: Option<i32>,
    /// The features included in this plan
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::BillingPlanFeaturesInner>>,
}

impl BillingPlan {
    pub fn new(object: Object, id: String, name: String, fee: models::BillingFee, annual_monthly_fee: Option<models::BillingFee>, annual_fee: Option<models::BillingFee>, description: Option<String>, product_id: String, is_default: bool, is_recurring: bool, publicly_visible: bool, has_base_fee: bool, for_payer_type: String, slug: String, avatar_url: Option<String>, free_trial_enabled: bool, free_trial_days: Option<i32>) -> BillingPlan {
        BillingPlan {
            object,
            id,
            name,
            fee: Box::new(fee),
            annual_monthly_fee: if let Some(x) = annual_monthly_fee {Some(Box::new(x))} else {None},
            annual_fee: if let Some(x) = annual_fee {Some(Box::new(x))} else {None},
            description,
            product_id,
            is_default,
            is_recurring,
            publicly_visible,
            has_base_fee,
            for_payer_type,
            slug,
            avatar_url,
            free_trial_enabled,
            free_trial_days,
            features: None,
        }
    }
}
/// String representing the object's type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "commerce_plan")]
    CommercePlan,
}

impl Default for Object {
    fn default() -> Object {
        Self::CommercePlan
    }
}

