/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingStatementResponseGroup {
    /// String representing the object's type
    #[serde(rename = "object")]
    pub object: String,
    /// Unix timestamp (in milliseconds) for the group
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    /// Payment items in this group
    #[serde(rename = "items")]
    pub items: Vec<models::BillingPaymentAttempt>,
}

impl BillingStatementResponseGroup {
    pub fn new(object: String, timestamp: i64, items: Vec<models::BillingPaymentAttempt>) -> BillingStatementResponseGroup {
        BillingStatementResponseGroup {
            object,
            timestamp,
            items,
        }
    }
}

