/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingPaymentMethodInitialize {
    /// String representing the object's type
    #[serde(rename = "object")]
    pub object: Object,
    /// Client secret from the payment gateway for setting up payment method
    #[serde(rename = "external_client_secret", skip_serializing_if = "Option::is_none")]
    pub external_client_secret: Option<String>,
    /// External gateway identifier
    #[serde(rename = "external_gateway_id", skip_serializing_if = "Option::is_none")]
    pub external_gateway_id: Option<String>,
    /// Ordered list of supported payment methods
    #[serde(rename = "payment_method_order")]
    pub payment_method_order: Vec<String>,
}

impl BillingPaymentMethodInitialize {
    pub fn new(object: Object, payment_method_order: Vec<String>) -> BillingPaymentMethodInitialize {
        BillingPaymentMethodInitialize {
            object,
            external_client_secret: None,
            external_gateway_id: None,
            payment_method_order,
        }
    }
}
/// String representing the object's type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "commerce_payment_method_initialize")]
    CommercePaymentMethodInitialize,
}

impl Default for Object {
    fn default() -> Object {
        Self::CommercePaymentMethodInitialize
    }
}

