/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingSubscriptionCreditResponse {
    #[serde(rename = "amount")]
    pub amount: Box<models::BillingMoneyResponse>,
    /// Number of days remaining in the billing cycle
    #[serde(rename = "cycle_days_remaining")]
    pub cycle_days_remaining: i64,
    /// Total number of days in the billing cycle
    #[serde(rename = "cycle_days_total")]
    pub cycle_days_total: i64,
    /// Percentage of the billing cycle remaining
    #[serde(rename = "cycle_remaining_percent")]
    pub cycle_remaining_percent: f64,
}

impl BillingSubscriptionCreditResponse {
    pub fn new(amount: models::BillingMoneyResponse, cycle_days_remaining: i64, cycle_days_total: i64, cycle_remaining_percent: f64) -> BillingSubscriptionCreditResponse {
        BillingSubscriptionCreditResponse {
            amount: Box::new(amount),
            cycle_days_remaining,
            cycle_days_total,
            cycle_remaining_percent,
        }
    }
}

