/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingStatement {
    /// String representing the object's type
    #[serde(rename = "object")]
    pub object: Object,
    /// Unique identifier for the instance
    #[serde(rename = "instance_id")]
    pub instance_id: String,
    /// Unique identifier for the statement
    #[serde(rename = "id")]
    pub id: String,
    /// Unix timestamp (in milliseconds) for the statement
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "payer")]
    pub payer: Box<models::BillingPayer>,
    /// Status of the statement
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "totals")]
    pub totals: Box<models::BillingStatementTotalsResponse>,
    /// Groups of payment items in the statement
    #[serde(rename = "groups")]
    pub groups: Vec<models::BillingStatementResponseGroup>,
}

impl BillingStatement {
    pub fn new(object: Object, instance_id: String, id: String, timestamp: i64, payer: models::BillingPayer, status: String, totals: models::BillingStatementTotalsResponse, groups: Vec<models::BillingStatementResponseGroup>) -> BillingStatement {
        BillingStatement {
            object,
            instance_id,
            id,
            timestamp,
            payer: Box::new(payer),
            status,
            totals: Box::new(totals),
            groups,
        }
    }
}
/// String representing the object's type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "commerce_statement")]
    CommerceStatement,
}

impl Default for Object {
    fn default() -> Object {
        Self::CommerceStatement
    }
}

