/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingPlanFeaturesInner {
    /// String representing the object's type
    #[serde(rename = "object")]
    pub object: Object,
    /// Unique identifier for the feature
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the feature
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the feature
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    /// URL-friendly representation of the feature's name
    #[serde(rename = "slug")]
    pub slug: String,
    /// URL for an image to represent the feature
    #[serde(rename = "avatar_url", deserialize_with = "Option::deserialize")]
    pub avatar_url: Option<String>,
}

impl BillingPlanFeaturesInner {
    pub fn new(object: Object, id: String, name: String, description: Option<String>, slug: String, avatar_url: Option<String>) -> BillingPlanFeaturesInner {
        BillingPlanFeaturesInner {
            object,
            id,
            name,
            description,
            slug,
            avatar_url,
        }
    }
}
/// String representing the object's type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "feature")]
    Feature,
}

impl Default for Object {
    fn default() -> Object {
        Self::Feature
    }
}

