/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientProtectConfigLoader : Configuration for the Clerk Protect loader.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientProtectConfigLoader {
    /// rollout percentage (between 0.0 and 1.0)
    #[serde(rename = "rollout", skip_serializing_if = "Option::is_none")]
    pub rollout: Option<f32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "textContent", skip_serializing_if = "Option::is_none")]
    pub text_content: Option<String>,
}

impl ClientProtectConfigLoader {
    /// Configuration for the Clerk Protect loader.
    pub fn new() -> ClientProtectConfigLoader {
        ClientProtectConfigLoader {
            rollout: None,
            r#type: None,
            target: None,
            attributes: None,
            text_content: None,
        }
    }
}

