/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientPhoneNumber {
    #[serde(rename = "id")]
    pub id: String,
    /// String representing the object's type. Objects of the same type share the same value. 
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "phone_number")]
    pub phone_number: String,
    #[serde(rename = "reserved_for_second_factor", skip_serializing_if = "Option::is_none")]
    pub reserved_for_second_factor: Option<bool>,
    #[serde(rename = "default_second_factor", skip_serializing_if = "Option::is_none")]
    pub default_second_factor: Option<bool>,
    #[serde(rename = "reserved")]
    pub reserved: bool,
    #[serde(rename = "verification", deserialize_with = "Option::deserialize")]
    pub verification: Option<Box<models::ClientPhoneNumberVerification>>,
    #[serde(rename = "linked_to")]
    pub linked_to: Vec<models::StubsIdentificationLink>,
    #[serde(rename = "backup_codes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub backup_codes: Option<Option<Vec<String>>>,
    /// Unix timestamp of creation 
    #[serde(rename = "created_at")]
    pub created_at: i64,
    /// Unix timestamp of creation 
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl ClientPhoneNumber {
    pub fn new(id: String, object: Object, phone_number: String, reserved: bool, verification: Option<models::ClientPhoneNumberVerification>, linked_to: Vec<models::StubsIdentificationLink>, created_at: i64, updated_at: i64) -> ClientPhoneNumber {
        ClientPhoneNumber {
            id,
            object,
            phone_number,
            reserved_for_second_factor: None,
            default_second_factor: None,
            reserved,
            verification: if let Some(x) = verification {Some(Box::new(x))} else {None},
            linked_to,
            backup_codes: None,
            created_at,
            updated_at,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "phone_number")]
    PhoneNumber,
}

impl Default for Object {
    fn default() -> Object {
        Self::PhoneNumber
    }
}

