/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientOrganizationMembershipRequest {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "public_user_data", deserialize_with = "Option::deserialize")]
    pub public_user_data: Option<Box<models::ClientPublicUserData>>,
    /// Unix timestamp of creation.
    #[serde(rename = "created_at")]
    pub created_at: i64,
    /// Unix timestamp of last update.
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl ClientOrganizationMembershipRequest {
    pub fn new(object: Object, id: String, organization_id: String, status: String, public_user_data: Option<models::ClientPublicUserData>, created_at: i64, updated_at: i64) -> ClientOrganizationMembershipRequest {
        ClientOrganizationMembershipRequest {
            object,
            id,
            organization_id,
            status,
            public_user_data: if let Some(x) = public_user_data {Some(Box::new(x))} else {None},
            created_at,
            updated_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "organization_membership_request")]
    OrganizationMembershipRequest,
}

impl Default for Object {
    fn default() -> Object {
        Self::OrganizationMembershipRequest
    }
}

