/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientPublicUserData {
    #[serde(rename = "first_name", deserialize_with = "Option::deserialize")]
    pub first_name: Option<String>,
    #[serde(rename = "last_name", deserialize_with = "Option::deserialize")]
    pub last_name: Option<String>,
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "has_image")]
    pub has_image: bool,
    #[serde(rename = "identifier")]
    pub identifier: String,
    /// Use `image_url` instead.
    #[serde(rename = "profile_image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub profile_image_url: Option<Option<String>>,
    #[serde(rename = "user_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<String>>,
    #[serde(rename = "username", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub username: Option<Option<String>>,
}

impl ClientPublicUserData {
    pub fn new(first_name: Option<String>, last_name: Option<String>, has_image: bool, identifier: String) -> ClientPublicUserData {
        ClientPublicUserData {
            first_name,
            last_name,
            image_url: None,
            has_image,
            identifier,
            profile_image_url: None,
            user_id: None,
            username: None,
        }
    }
}

