/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientOrganizationSettings {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "max_allowed_memberships")]
    pub max_allowed_memberships: i32,
    #[serde(rename = "actions")]
    pub actions: Box<models::OrganizationSettingsActionsSettings>,
    #[serde(rename = "domains")]
    pub domains: Box<models::OrganizationSettingsDomainsSettings>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<Box<models::OrganizationSettingsSlugSettings>>,
    /// The role key that a user will be assigned after creating an organization.
    #[serde(rename = "creator_role")]
    pub creator_role: String,
}

impl ClientOrganizationSettings {
    pub fn new(enabled: bool, max_allowed_memberships: i32, actions: models::OrganizationSettingsActionsSettings, domains: models::OrganizationSettingsDomainsSettings, creator_role: String) -> ClientOrganizationSettings {
        ClientOrganizationSettings {
            enabled,
            max_allowed_memberships,
            actions: Box::new(actions),
            domains: Box::new(domains),
            slug: None,
            creator_role,
        }
    }
}

