/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientAccountPortalCustomization {
    #[serde(rename = "appearance", deserialize_with = "Option::deserialize")]
    pub appearance: Option<Appearance>,
    #[serde(rename = "background_color_dark", deserialize_with = "Option::deserialize")]
    pub background_color_dark: Option<String>,
    #[serde(rename = "background_color_light", deserialize_with = "Option::deserialize")]
    pub background_color_light: Option<String>,
    #[serde(rename = "primary_color_dark", deserialize_with = "Option::deserialize")]
    pub primary_color_dark: Option<String>,
    #[serde(rename = "primary_color_light", deserialize_with = "Option::deserialize")]
    pub primary_color_light: Option<String>,
}

impl ClientAccountPortalCustomization {
    pub fn new(appearance: Option<Appearance>, background_color_dark: Option<String>, background_color_light: Option<String>, primary_color_dark: Option<String>, primary_color_light: Option<String>) -> ClientAccountPortalCustomization {
        ClientAccountPortalCustomization {
            appearance,
            background_color_dark,
            background_color_light,
            primary_color_dark,
            primary_color_light,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Appearance {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "dark")]
    Dark,
    #[serde(rename = "light")]
    Light,
}

impl Default for Appearance {
    fn default() -> Appearance {
        Self::Auto
    }
}

