/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClientSignUpVerificationsExternalAccount {
    StubsVerificationOauth(Box<models::StubsVerificationOauth>),
    StubsVerificationSaml(Box<models::StubsVerificationSaml>),
    StubsVerificationTicket(Box<models::StubsVerificationTicket>),
    StubsVerificationGoogleOneTap(Box<models::StubsVerificationGoogleOneTap>),
}

impl Default for ClientSignUpVerificationsExternalAccount {
    fn default() -> Self {
        Self::StubsVerificationOauth(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "verification_google_one_tap")]
    VerificationGoogleOneTap,
}

impl Default for Object {
    fn default() -> Object {
        Self::VerificationGoogleOneTap
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "unverified")]
    Unverified,
    #[serde(rename = "verified")]
    Verified,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unverified
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
    #[serde(rename = "google_one_tap")]
    GoogleOneTap,
}

impl Default for Strategy {
    fn default() -> Strategy {
        Self::GoogleOneTap
    }
}

