/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKey201Response {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "claims", deserialize_with = "Option::deserialize")]
    pub claims: Option<serde_json::Value>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "revoked")]
    pub revoked: bool,
    #[serde(rename = "revocation_reason", deserialize_with = "Option::deserialize")]
    pub revocation_reason: Option<String>,
    #[serde(rename = "expired")]
    pub expired: bool,
    #[serde(rename = "expiration", deserialize_with = "Option::deserialize")]
    pub expiration: Option<f64>,
    #[serde(rename = "created_by", deserialize_with = "Option::deserialize")]
    pub created_by: Option<String>,
    #[serde(rename = "last_used_at", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<f64>,
    #[serde(rename = "created_at")]
    pub created_at: f64,
    #[serde(rename = "updated_at")]
    pub updated_at: f64,
}

impl CreateApiKey201Response {
    pub fn new(object: Object, id: String, r#type: String, subject: String, name: String, claims: Option<serde_json::Value>, scopes: Vec<String>, secret: String, revoked: bool, revocation_reason: Option<String>, expired: bool, expiration: Option<f64>, created_by: Option<String>, last_used_at: Option<f64>, created_at: f64, updated_at: f64) -> CreateApiKey201Response {
        CreateApiKey201Response {
            object,
            id,
            r#type,
            subject,
            name,
            description: None,
            claims,
            scopes,
            secret,
            revoked,
            revocation_reason,
            expired,
            expiration,
            created_by,
            last_used_at,
            created_at,
            updated_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "api_key")]
    ApiKey,
}

impl Default for Object {
    fn default() -> Object {
        Self::ApiKey
    }
}

