/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JwksKeysInner {
    JwksEd25519PublicKey(Box<models::JwksEd25519PublicKey>),
    JwksEcdsaPublicKey(Box<models::JwksEcdsaPublicKey>),
    JwksRsaPublicKey(Box<models::JwksRsaPublicKey>),
    JwksEd25519PrivateKey(Box<models::JwksEd25519PrivateKey>),
    JwksEcdsaPrivateKey(Box<models::JwksEcdsaPrivateKey>),
    JwksRsaPrivateKey(Box<models::JwksRsaPrivateKey>),
    JwksSymmetricKey(Box<models::JwksSymmetricKey>),
}

impl Default for JwksKeysInner {
    fn default() -> Self {
        Self::JwksEd25519PublicKey(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kty {
    #[serde(rename = "oct")]
    Oct,
}

impl Default for Kty {
    fn default() -> Kty {
        Self::Oct
    }
}

