/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthDynamicClientRegistrationError : Error response for OAuth 2.0 Dynamic Client Registration according to RFC 7591. The error response uses OAuth 2.0 error response format.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthDynamicClientRegistrationError {
    /// Single ASCII error code string indicating the error type. - `invalid_redirect_uri`: The value of one or more redirect_uris is invalid - `invalid_client_metadata`: One or more client metadata fields is invalid - `invalid_software_statement`: The software statement presented is invalid - `unapproved_software_statement`: The software statement is not approved
    #[serde(rename = "error")]
    pub error: Error,
    /// Human-readable ASCII text description of the error used for debugging. This is not meant to be displayed to the end-user.
    #[serde(rename = "error_description", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
}

impl OAuthDynamicClientRegistrationError {
    /// Error response for OAuth 2.0 Dynamic Client Registration according to RFC 7591. The error response uses OAuth 2.0 error response format.
    pub fn new(error: Error) -> OAuthDynamicClientRegistrationError {
        OAuthDynamicClientRegistrationError {
            error,
            error_description: None,
        }
    }
}
/// Single ASCII error code string indicating the error type. - `invalid_redirect_uri`: The value of one or more redirect_uris is invalid - `invalid_client_metadata`: One or more client metadata fields is invalid - `invalid_software_statement`: The software statement presented is invalid - `unapproved_software_statement`: The software statement is not approved
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "invalid_redirect_uri")]
    InvalidRedirectUri,
    #[serde(rename = "invalid_client_metadata")]
    InvalidClientMetadata,
    #[serde(rename = "invalid_software_statement")]
    InvalidSoftwareStatement,
    #[serde(rename = "unapproved_software_statement")]
    UnapprovedSoftwareStatement,
}

impl Default for Error {
    fn default() -> Error {
        Self::InvalidRedirectUri
    }
}

