/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthDynamicClientRegistrationRequest : Client metadata used to register a new OAuth 2.0 client according to RFC 7591. The authorization server assigns this client a unique client identifier.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthDynamicClientRegistrationRequest {
    /// Array of redirection URI strings for use in redirect-based flows such as the authorization code flow. As required by Section 2 of RFC 6749, clients using flows with redirection must register their redirection URI values.
    #[serde(rename = "redirect_uris")]
    pub redirect_uris: Vec<String>,
    /// Indicator of the requested authentication method for the token endpoint. - `client_secret_basic`: HTTP Basic authentication scheme - `client_secret_post`: Client credentials in the request body - `none`: Public client (no authentication)  **Note:** In the current implementation, `client_secret_basic` and `client_secret_post` are treated equivalently. Both methods can be used interchangeably at the token endpoint regardless of which one was specified during registration.
    #[serde(rename = "token_endpoint_auth_method", skip_serializing_if = "Option::is_none")]
    pub token_endpoint_auth_method: Option<TokenEndpointAuthMethod>,
    /// Human-readable string name of the client to be presented to the end-user during authorization.
    #[serde(rename = "client_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_name: Option<Option<String>>,
    /// URL string of a web page providing information about the client.
    #[serde(rename = "client_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_uri: Option<Option<String>>,
    /// URL string that references a logo for the client. If present, the Clerk will display this image to the end-user during approval.
    #[serde(rename = "logo_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_uri: Option<Option<String>>,
    /// Space-separated list of scope values that the client can use when requesting access tokens. If omitted, the client will be registered with the default set of scopes.
    #[serde(rename = "scope", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Option<String>>,
}

impl OAuthDynamicClientRegistrationRequest {
    /// Client metadata used to register a new OAuth 2.0 client according to RFC 7591. The authorization server assigns this client a unique client identifier.
    pub fn new(redirect_uris: Vec<String>) -> OAuthDynamicClientRegistrationRequest {
        OAuthDynamicClientRegistrationRequest {
            redirect_uris,
            token_endpoint_auth_method: None,
            client_name: None,
            client_uri: None,
            logo_uri: None,
            scope: None,
        }
    }
}
/// Indicator of the requested authentication method for the token endpoint. - `client_secret_basic`: HTTP Basic authentication scheme - `client_secret_post`: Client credentials in the request body - `none`: Public client (no authentication)  **Note:** In the current implementation, `client_secret_basic` and `client_secret_post` are treated equivalently. Both methods can be used interchangeably at the token endpoint regardless of which one was specified during registration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenEndpointAuthMethod {
    #[serde(rename = "client_secret_basic")]
    ClientSecretBasic,
    #[serde(rename = "client_secret_post")]
    ClientSecretPost,
    #[serde(rename = "none")]
    None,
}

impl Default for TokenEndpointAuthMethod {
    fn default() -> TokenEndpointAuthMethod {
        Self::ClientSecretBasic
    }
}

