/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationSettingsDomainsSettings {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "enrollment_modes")]
    pub enrollment_modes: Vec<EnrollmentModes>,
    /// The role key that it will be used in order to create an organization invitation or suggestion.
    #[serde(rename = "default_role")]
    pub default_role: String,
}

impl OrganizationSettingsDomainsSettings {
    pub fn new(enabled: bool, enrollment_modes: Vec<EnrollmentModes>, default_role: String) -> OrganizationSettingsDomainsSettings {
        OrganizationSettingsDomainsSettings {
            enabled,
            enrollment_modes,
            default_role,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnrollmentModes {
    #[serde(rename = "manual_invitation")]
    ManualInvitation,
    #[serde(rename = "automatic_invitation")]
    AutomaticInvitation,
    #[serde(rename = "automatic_suggestion")]
    AutomaticSuggestion,
}

impl Default for EnrollmentModes {
    fn default() -> EnrollmentModes {
        Self::ManualInvitation
    }
}

