/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemasClientSession {
    #[serde(rename = "id")]
    pub id: String,
    /// String representing the object's type. Objects of the same type share the same value. 
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "expire_at")]
    pub expire_at: i64,
    #[serde(rename = "abandon_at")]
    pub abandon_at: i64,
    #[serde(rename = "last_active_at")]
    pub last_active_at: i64,
    #[serde(rename = "last_active_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_active_token: Option<Option<Box<models::Token>>>,
    #[serde(rename = "actor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub actor: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "last_active_organization_id", deserialize_with = "Option::deserialize")]
    pub last_active_organization_id: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::ClientUser>>,
    #[serde(rename = "public_user_data", deserialize_with = "Option::deserialize")]
    pub public_user_data: Option<serde_json::Value>,
    /// Each item represents the minutes that have passed since the last time a first or second factor were verified.
    #[serde(rename = "factor_verification_age")]
    pub factor_verification_age: Vec<i32>,
    /// Unix timestamp of creation.
    #[serde(rename = "created_at")]
    pub created_at: i64,
    /// Unix timestamp of last update.
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl SchemasClientSession {
    pub fn new(id: String, object: Object, status: Status, expire_at: i64, abandon_at: i64, last_active_at: i64, last_active_organization_id: Option<String>, public_user_data: Option<serde_json::Value>, factor_verification_age: Vec<i32>, created_at: i64, updated_at: i64) -> SchemasClientSession {
        SchemasClientSession {
            id,
            object,
            status,
            expire_at,
            abandon_at,
            last_active_at,
            last_active_token: None,
            actor: None,
            last_active_organization_id,
            user: None,
            public_user_data,
            factor_verification_age,
            created_at,
            updated_at,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "session")]
    Session,
}

impl Default for Object {
    fn default() -> Object {
        Self::Session
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "ended")]
    Ended,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "removed")]
    Removed,
    #[serde(rename = "abandoned")]
    Abandoned,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

