/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsAttribute {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "used_for_first_factor")]
    pub used_for_first_factor: bool,
    #[serde(rename = "first_factors")]
    pub first_factors: Vec<String>,
    #[serde(rename = "used_for_second_factor")]
    pub used_for_second_factor: bool,
    #[serde(rename = "second_factors")]
    pub second_factors: Vec<String>,
    #[serde(rename = "verifications")]
    pub verifications: Vec<String>,
    #[serde(rename = "verify_at_sign_up")]
    pub verify_at_sign_up: bool,
}

impl UserSettingsAttribute {
    pub fn new(enabled: bool, required: bool, used_for_first_factor: bool, first_factors: Vec<String>, used_for_second_factor: bool, second_factors: Vec<String>, verifications: Vec<String>, verify_at_sign_up: bool) -> UserSettingsAttribute {
        UserSettingsAttribute {
            enabled,
            required,
            used_for_first_factor,
            first_factors,
            used_for_second_factor,
            second_factors,
            verifications,
            verify_at_sign_up,
        }
    }
}

